export const RESTAURANT = {
  name: 'Chopras Indian Restaurant',
  tagline: 'Authentic Indian Street Food in Den Haag',
  address: {
    street: 'Leyweg 986',
    postcode: '2545 GW',
    city: 'Den Haag',
    country: 'Netherlands',
    countryCode: 'NL',
    full: 'Leyweg 986, 2545 GW Den Haag, Netherlands',
    coordinates: { lat: 52.04874, lng: 4.27684 },
  },
  contact: {
    phone: '+31630645930',
    phoneDisplay: '+31 6 30645930',
    email: 'info@chopras.nl',
    website: 'https://chopras.nl',
  },
  hours: [
    { day: 'Monday', dayNl: 'Maandag', open: false },
    { day: 'Tuesday', dayNl: 'Dinsdag', open: true, from: '16:30', to: '22:30' },
    { day: 'Wednesday', dayNl: 'Woensdag', open: true, from: '16:30', to: '22:30' },
    { day: 'Thursday', dayNl: 'Donderdag', open: true, from: '16:30', to: '22:30' },
    { day: 'Friday', dayNl: 'Vrijdag', open: true, from: '16:30', to: '22:30' },
    { day: 'Saturday', dayNl: 'Zaterdag', open: true, from: '16:30', to: '22:30' },
    { day: 'Sunday', dayNl: 'Zondag', open: true, from: '16:30', to: '22:30' },
  ],
  social: {
    tripadvisor: 'https://www.tripadvisor.com/Restaurant_Review-g188633-d27464805-Reviews-Chopras_Indian_Restaurant-The_Hague_South_Holland_Province.html',
    facebook: 'https://www.facebook.com/choprasrestaurant',
    instagram: 'https://www.instagram.com/choprasrestaurant',
    youtube: 'https://www.youtube.com/@choprasrestaurant',
    thefork: 'https://www.thefork.nl/restaurant/chopras-indian-restaurant-r825662',
    thuisbezorgd: 'https://www.thuisbezorgd.nl/menu/chopras-indian-street-food',
    ubereats: 'https://www.ubereats.com/nl/store/chopras-indian-restaurant/kFKhBtR-W3OkJyl2f6QmUg',
  },
  googlePlaceId: 'ChIJDUXdqSuxxUcRa6FxjpzGMvk',
  googleMapsUrl: 'https://www.google.com/maps/place/?q=place_id:ChIJDUXdqSuxxUcRa6FxjpzGMvk',
  reviewUrl: 'https://search.google.com/local/writereview?placeid=ChIJDUXdqSuxxUcRa6FxjpzGMvk',
  logo: 'https://chopras.nl/logo.png',
  cuisines: ['North Indian', 'Indo-Chinese', 'Indian Street Food'],
  features: [
    'Halal Certified',
    'Vegetarian Options',
    'Vegan Options',
    'Wheelchair Accessible',
    'Family Friendly',
    'Pet Friendly',
    'Private Event Hall',
    'Catering Available',
  ],
  serviceAreas: ['Den Haag', 'Rijswijk', 'Delft', 'Zoetermeer', 'Voorburg', 'Leidschendam', 'Westland'],
  priceRange: '€€',
} as const

export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://chopras.nl'
