import type { MenuItem, MenuCategory } from '@/types'

export type MenuCategoryEntry = {
  id: MenuCategory
  label: string
  labelNl: string
  shortLabel: string
}

export const categoryLabels: Record<MenuCategory, { label: string; labelNl: string }> = {
  starters: {
    label: 'Indian Starters and Street Food in Den Haag',
    labelNl: 'Indiase Starters en Streetfood in Den Haag',
  },
  soups: {
    label: 'Indian Soups in Den Haag',
    labelNl: 'Indiase Soepen in Den Haag',
  },
  tandoori: {
    label: 'Tandoori - Clay Oven Grill Specialties',
    labelNl: 'Tandoori Gerechten - Specialiteiten uit de Kleistenen Oven',
  },
  'veg-curries': {
    label: 'Vegetarian Indian Curries in Den Haag',
    labelNl: 'Vegetarische Indiase Curries in Den Haag',
  },
  chicken: {
    label: 'Chicken Curries in Den Haag',
    labelNl: 'Kip Curries in Den Haag',
  },
  'lamb-mutton': {
    label: 'Lamb and Mutton Curries in Den Haag',
    labelNl: 'Lam en Schapenvlees Curries in Den Haag',
  },
  'indo-chinese': {
    label: 'Indo-Chinese Dishes in Den Haag',
    labelNl: 'Indo-Chinese Gerechten in Den Haag',
  },
  biryani: {
    label: 'Biryani in Den Haag',
    labelNl: 'Biryani in Den Haag',
  },
  breads: {
    label: 'Indian Breads Baked Fresh in the Tandoor',
    labelNl: 'Indiaas Brood Vers Gebakken in de Tandoor',
  },
  'rice-sides': {
    label: 'Rice, Sides and Thali',
    labelNl: 'Rijst, Bijgerechten en Thali',
  },
  desserts: {
    label: 'Indian Desserts in Den Haag',
    labelNl: 'Indiase Desserts in Den Haag',
  },
  drinks: {
    label: 'Drinks and Lassi in Den Haag',
    labelNl: 'Dranken en Lassi in Den Haag',
  },
}

export const menuCategories: MenuCategoryEntry[] = [
  {
    id: 'starters',
    label: categoryLabels['starters'].label,
    labelNl: categoryLabels['starters'].labelNl,
    shortLabel: 'Starters',
  },
  {
    id: 'soups',
    label: categoryLabels['soups'].label,
    labelNl: categoryLabels['soups'].labelNl,
    shortLabel: 'Soups',
  },
  {
    id: 'tandoori',
    label: categoryLabels['tandoori'].label,
    labelNl: categoryLabels['tandoori'].labelNl,
    shortLabel: 'Tandoori',
  },
  {
    id: 'veg-curries',
    label: categoryLabels['veg-curries'].label,
    labelNl: categoryLabels['veg-curries'].labelNl,
    shortLabel: 'Veg Curries',
  },
  {
    id: 'chicken',
    label: categoryLabels['chicken'].label,
    labelNl: categoryLabels['chicken'].labelNl,
    shortLabel: 'Chicken',
  },
  {
    id: 'lamb-mutton',
    label: categoryLabels['lamb-mutton'].label,
    labelNl: categoryLabels['lamb-mutton'].labelNl,
    shortLabel: 'Lamb & Mutton',
  },
  {
    id: 'indo-chinese',
    label: categoryLabels['indo-chinese'].label,
    labelNl: categoryLabels['indo-chinese'].labelNl,
    shortLabel: 'Indo-Chinese',
  },
  {
    id: 'biryani',
    label: categoryLabels['biryani'].label,
    labelNl: categoryLabels['biryani'].labelNl,
    shortLabel: 'Biryani',
  },
  {
    id: 'breads',
    label: categoryLabels['breads'].label,
    labelNl: categoryLabels['breads'].labelNl,
    shortLabel: 'Breads',
  },
  {
    id: 'rice-sides',
    label: categoryLabels['rice-sides'].label,
    labelNl: categoryLabels['rice-sides'].labelNl,
    shortLabel: 'Rice & Sides',
  },
  {
    id: 'desserts',
    label: categoryLabels['desserts'].label,
    labelNl: categoryLabels['desserts'].labelNl,
    shortLabel: 'Desserts',
  },
  {
    id: 'drinks',
    label: categoryLabels['drinks'].label,
    labelNl: categoryLabels['drinks'].labelNl,
    shortLabel: 'Drinks',
  },
]

export const menuItems: MenuItem[] = [
  // ─── STARTERS ────────────────────────────────────────────────────────────
  {
    id: 'onion-bhaji',
    name: 'Onion Bhaji',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/onion-bhaji.webp',
    description: '',
  },
  {
    id: 'samosa',
    name: 'Samosa (Veg/Lamb/Chicken)',
    price: 8,
    category: 'starters',
    dietary: ['halal'],
    image: '/images/dishes/veg-samosa.webp',
    description: '',
  },
  {
    id: 'veg-samosa-chaat',
    name: 'Veg Samosa Chaat',
    price: 10,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/samosa-chaat.webp',
    description: '',
  },
  {
    id: 'pani-puri',
    name: 'Pani Puri',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/pani-puri.webp',
    description: '',
  },
  {
    id: 'dahi-puri',
    name: 'Dahi Puri',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dahi-puri.webp',
    description: '',
  },
  {
    id: 'aloo-tikki',
    name: 'Aloo Tikki',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-tikki.webp',
    description: '',
  },
  {
    id: 'papdi-chaat',
    name: 'Papdi Chaat',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/papdi-chaat.webp',
    description: '',
  },
  {
    id: 'mixed-chaat',
    name: 'Mixed Chaat',
    price: 12,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-chaat.webp',
    description: '',
  },
  {
    id: 'plain-papad',
    name: 'Plain Papad',
    price: 3.5,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-papad.webp',
    description: '',
  },
  {
    id: 'masala-papad',
    name: 'Masala Papad',
    price: 5,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/masala-papad.webp',
    description: '',
  },

  // ─── TANDOORI ────────────────────────────────────────────────────────────
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-tikka.webp',
    description: '',
  },
  {
    id: 'malai-soya-chaap',
    name: 'Malai Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-soya-chap.webp',
    description: '',
  },
  {
    id: 'achari-soya-chaap',
    name: 'Achari Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/soya-chaap-achari.webp',
    description: '',
  },
  {
    id: 'tandoori-prawn-fish',
    name: 'Tandoori Prawn/Fish',
    price: 24.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-prawns.webp',
    description: '',
  },
  {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-chicken.webp',
    description: '',
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka.webp',
    description: '',
  },
  {
    id: 'chicken-malai-tikka',
    name: 'Chicken Malai Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-malai-tikka.webp',
    description: '',
  },
  {
    id: 'chicken-hariyali-tikka',
    name: 'Chicken Hariyali Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-hariyali-tikka.webp',
    description: '',
  },
  {
    id: 'chicken-lasooni-tikka',
    name: 'Chicken Lasooni Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-lasooni-tikka.webp',
    description: '',
  },
  {
    id: 'lamb-seekh-kebab',
    name: 'Lamb Seekh Kebab',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-kebab.webp',
    description: '',
  },
  {
    id: 'chicken-seekh-kebab',
    name: 'Chicken Seekh Kebab',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-seekh-kebab.webp',
    description: '',
  },
  {
    id: 'chopras-non-veg-platter',
    name: 'Chopras Non Veg Platter',
    price: 30,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chopras-non-veg-platter.webp',
    description: '',
  },

  // ─── SOUPS ───────────────────────────────────────────────────────────────
  {
    id: 'tomato-soup',
    name: 'Tomato Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tomato-soup.webp',
    description: '',
  },
  {
    id: 'lentil-soup',
    name: 'Lentil Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-soup.webp',
    description: '',
  },
  {
    id: 'veg-manchow-soup',
    name: 'Veg Manchow Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/manchow-soup.webp',
    description: '',
  },
  {
    id: 'chicken-soup',
    name: 'Chicken Soup',
    price: 8.5,
    category: 'soups',
    dietary: ['halal'],
    image: '/images/dishes/chicken-soup.webp',
    description: '',
  },

  // ─── VEG CURRIES (Veg Curries + Paneer Curries) ──────────────────────────
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    price: 18.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-makhani.webp',
    description: '',
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    price: 15,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-tadka.webp',
    description: '',
  },
  {
    id: 'rajma-raseela',
    name: 'Rajma Raseela',
    price: 15,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/rajma-masala.webp',
    description: '',
  },
  {
    id: 'chana-masala',
    name: 'Chana Masala',
    price: 16,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/channa-masala.webp',
    description: '',
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    price: 14,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-gobhi.webp',
    description: '',
  },
  {
    id: 'aloo-jeera',
    name: 'Aloo Jeera',
    price: 12.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-jeera.webp',
    description: '',
  },
  {
    id: 'mixed-veg',
    name: 'Mixed Veg',
    price: 15,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-veg.webp',
    description: '',
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    price: 14,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/bhandi-masala.webp',
    description: '',
  },
  {
    id: 'baingan-bharta',
    name: 'Baingan Bharta',
    price: 14,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/baingan-bharta.webp',
    description: '',
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    price: 18.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kofta.webp',
    description: '',
  },
  // Paneer Curries (grouped under veg-curries)
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/palak-paneer.webp',
    description: '',
  },
  {
    id: 'karahi-paneer',
    name: 'Karahi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/karahi-paneer.webp',
    description: '',
  },
  {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/shahi-paneer.webp',
    description: '',
  },
  {
    id: 'handi-paneer',
    name: 'Handi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/handi-paneer.webp',
    description: '',
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-butter-masala.webp',
    description: '',
  },
  {
    id: 'tawa-paneer-masala',
    name: 'Tawa Paneer Masala',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tawa-paneer.webp',
    description: '',
  },
  {
    id: 'chopras-special-paneer',
    name: 'Chopras Special Paneer',
    price: 20,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chopras-special-paneer.webp',
    description: '',
  },

  // ─── CHICKEN ─────────────────────────────────────────────────────────────
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    price: 20,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/butter-chicken.webp',
    description: '',
  },
  {
    id: 'karahi-chicken',
    name: 'Karahi Chicken',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/kadai-chicken.webp',
    description: '',
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-curry.webp',
    description: '',
  },
  {
    id: 'chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    price: 20,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-masala.webp',
    description: '',
  },
  {
    id: 'chicken-handi',
    name: 'Chicken Handi',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-handi.webp',
    description: '',
  },
  {
    id: 'chicken-vindaloo',
    name: 'Chicken Vindaloo',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-vindaloo.webp',
    description: '',
  },
  {
    id: 'chicken-methi-malai',
    name: 'Chicken Methi Malai',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-methi-malai.webp',
    description: '',
  },

  // ─── LAMB & MUTTON ───────────────────────────────────────────────────────
  {
    id: 'mutton-rogan-josh',
    name: 'Mutton Rogan Josh',
    price: 22.5,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-rogan-josh.webp',
    description: '',
  },
  {
    id: 'mutton-vindaloo',
    name: 'Mutton Vindaloo',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-vindaloo.webp',
    description: '',
  },
  {
    id: 'tawa-mutton-masala',
    name: 'Tawa Mutton Masala',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/tawa-mutton-masala.webp',
    description: '',
  },
  {
    id: 'mutton-karahi',
    name: 'Mutton Karahi',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-karahi.webp',
    description: '',
  },
  {
    id: 'mutton-korma',
    name: 'Mutton Korma',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-korma.webp',
    description: '',
  },
  {
    id: 'mutton-handi',
    name: 'Mutton Handi',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/handi-mutton.webp',
    description: '',
  },
  {
    id: 'rara-gosht',
    name: 'Rara Gosht',
    price: 25,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/rara-gosht.webp',
    description: '',
  },
  {
    id: 'keema-saag',
    name: 'Keema Saag',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/keema-saag.webp',
    description: '',
  },

  // ─── INDO-CHINESE ────────────────────────────────────────────────────────
  {
    id: 'veg-spring-roll',
    name: 'Veg Spring Roll',
    price: 10,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-spring-roll.webp',
    description: '',
  },
  {
    id: 'chicken-spring-roll',
    name: 'Chicken Spring Roll',
    price: 11,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chicken-spring-roll.webp',
    description: '',
  },
  {
    id: 'chilli-paneer',
    name: 'Chilli Paneer',
    price: 18,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chilli-paneer.webp',
    description: '',
  },
  {
    id: 'chilli-chicken',
    name: 'Chilli Chicken',
    price: 20,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chilli-chicken.webp',
    description: '',
  },
  {
    id: 'veg-noodles',
    name: 'Veg Noodles',
    price: 14.5,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-noodles.webp',
    description: '',
  },

  // ─── BIRYANI ─────────────────────────────────────────────────────────────
  {
    id: 'veg-biryani',
    name: 'Veg Biryani',
    price: 15,
    category: 'biryani',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-biryani.webp',
    description: '',
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    price: 19,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/chicken-biryani.webp',
    description: '',
  },
  {
    id: 'prawn-biryani',
    name: 'Prawn Biryani',
    price: 23,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/prawns-biryani.webp',
    description: '',
  },
  {
    id: 'lamb-biryani',
    name: 'Lamb Biryani',
    price: 22,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/muton-biryani.webp',
    description: '',
  },

  // ─── BREADS (Bread + Rolls) ───────────────────────────────────────────────
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    price: 3,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tandoori-roti.webp',
    description: '',
  },
  {
    id: 'butter-roti',
    name: 'Butter Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tandoori-butter-roti.webp',
    description: '',
  },
  {
    id: 'onion-roti',
    name: 'Onion Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/onion-tandoori-roti.webp',
    description: '',
  },
  {
    id: 'garlic-roti',
    name: 'Garlic Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-roti.webp',
    description: '',
  },
  {
    id: 'missi-roti',
    name: 'Missi Roti',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/missi-roti.webp',
    description: '',
  },
  {
    id: 'lachha-paratha',
    name: 'Lachha Paratha',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/laccha-paratha.webp',
    description: '',
  },
  {
    id: 'pudina-paratha',
    name: 'Pudina Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mint-paratha.webp',
    description: '',
  },
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-paratha.webp',
    description: '',
  },
  {
    id: 'paneer-paratha',
    name: 'Paneer Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-paratha.webp',
    description: '',
  },
  {
    id: 'plain-naan',
    name: 'Plain Naan',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-naan.webp',
    description: '',
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/butter-naan.webp',
    description: '',
  },
  {
    id: 'garlic-naan',
    name: 'Garlic Naan',
    price: 4.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-naan.webp',
    description: '',
  },
  {
    id: 'paneer-naan',
    name: 'Paneer Naan',
    price: 6,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-naan.webp',
    description: '',
  },
  {
    id: 'cheese-naan',
    name: 'Cheese Naan',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cheese-naan.webp',
    description: '',
  },
  {
    id: 'keema-naan',
    name: 'Keema Naan',
    price: 7,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/keema-naan.webp',
    description: '',
  },
  // Rolls (grouped under breads)
  {
    id: 'paneer-roll',
    name: 'Paneer Roll',
    price: 12,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-roll.webp',
    description: '',
  },
  {
    id: 'egg-kathi-roll',
    name: 'Egg Kathi Roll',
    price: 12,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/egg-roll.webp',
    description: '',
  },
  {
    id: 'chicken-tikka-roll',
    name: 'Chicken Tikka Roll',
    price: 14,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-roll.webp',
    description: '',
  },
  {
    id: 'mutton-seekh-roll',
    name: 'Mutton Seekh Roll',
    price: 16,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-roll.webp',
    description: '',
  },

  // ─── RICE & SIDES (Rice non-biryani + Thali + Kids + Sides) ─────────────
  {
    id: 'steamed-rice',
    name: 'Steamed Rice',
    price: 7.5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/steamed-rice.webp',
    description: '',
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    price: 10,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/jeera-rice.webp',
    description: '',
  },
  {
    id: 'veg-fried-rice',
    name: 'Veg Fried Rice',
    price: 14,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-fried-rice.webp',
    description: '',
  },
  {
    id: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    price: 18,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/chicken-fried-rice.webp',
    description: '',
  },
  {
    id: 'veg-thali',
    name: 'Veg Thali',
    price: 30,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-thali.webp',
    description: '',
  },
  {
    id: 'non-veg-thali',
    name: 'Non Veg Thali',
    price: 35,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/non-veg-thali.webp',
    description: '',
  },
  {
    id: 'fries-nuggets',
    name: 'Fries & Nuggets',
    price: 7,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/fries-chicken-nuggets-kids.webp',
    description: '',
  },
  {
    id: 'onion-salad',
    name: 'Onion Salad',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/onion-salad.webp',
    description: '',
  },
  {
    id: 'mixed-salad',
    name: 'Mixed Salad',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-salad.webp',
    description: '',
  },
  {
    id: 'boondi-raita',
    name: 'Boondi Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/boondi-raita.webp',
    description: '',
  },
  {
    id: 'cucumber-raita',
    name: 'Cucumber Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cucumber-raita.webp',
    description: '',
  },
  {
    id: 'mixed-raita',
    name: 'Mixed Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-raita.webp',
    description: '',
  },
  {
    id: 'green-chillies',
    name: 'Green Chillies',
    price: 2,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/green-chilli.webp',
    description: '',
  },
  {
    id: 'mixed-pickle',
    name: 'Mixed Pickle',
    price: 3,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-pickle.webp',
    description: '',
  },
  {
    id: 'mint-chutney',
    name: 'Mint Chutney',
    price: 2,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'tamarind-chutney',
    name: 'Tamarind Chutney',
    price: 2,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'vinegar-onion',
    name: 'Vinegar Onion',
    price: 2,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },

  // ─── DESSERTS ────────────────────────────────────────────────────────────
  {
    id: 'moong-dal-halwa',
    name: 'Moong Dal Halwa',
    price: 8,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/moong-dal-halwa.webp',
    description: '',
  },
  {
    id: 'saffron-kheer',
    name: 'Saffron Kheer',
    price: 5.5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/saffron-kheer.webp',
    description: '',
  },
  {
    id: 'rasmalai',
    name: 'Rasmalai',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/rasmalai.webp',
    description: '',
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/gulab-jamun.webp',
    description: '',
  },
  {
    id: 'kulfi-pistachio',
    name: 'Kulfi Pistachio',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/pista-kulfi.webp',
    description: '',
  },
  {
    id: 'kulfi-malai',
    name: 'Kulfi Malai',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kulfi.webp',
    description: '',
  },
  {
    id: 'kulfi-coconut',
    name: 'Kulfi Coconut',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/coconut-kulfi.webp',
    description: '',
  },
  {
    id: 'kulfi-mango',
    name: 'Kulfi Mango',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-kulfi.webp',
    description: '',
  },
  {
    id: 'ice-cream-vanilla',
    name: 'Ice Cream Vanilla',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'ice-cream-chocolate',
    name: 'Ice Cream Chocolate',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'ice-cream-strawberry',
    name: 'Ice Cream Strawberry',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },

  // ─── DRINKS ──────────────────────────────────────────────────────────────
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    price: 6,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-lassi.webp',
    description: '',
  },
  {
    id: 'salted-lassi',
    name: 'Salted Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/salted-lassi.webp',
    description: '',
  },
  {
    id: 'sweet-lassi',
    name: 'Sweet Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/sweet-lassi.webp',
    description: '',
  },
  {
    id: 'shikanji',
    name: 'Shikanji',
    price: 4.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/shikanji.webp',
    description: '',
  },
  {
    id: 'jal-jeera',
    name: 'Jal Jeera',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/jal-jeera.webp',
    description: '',
  },
  {
    id: 'masala-soda',
    name: 'Masala Soda',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/masala-soda.webp',
    description: '',
  },
  {
    id: 'masala-coke',
    name: 'Masala Coke',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/masala-coke.webp',
    description: '',
  },
  {
    id: 'masala-tea',
    name: 'Masala Tea',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/indian-masala-tea.webp',
    description: '',
  },
  {
    id: 'thums-up',
    name: 'Thums Up',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'limca',
    name: 'Limca',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'maaza',
    name: 'Maaza',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'cola-cola-zero',
    name: 'Cola / Cola Zero',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'fanta',
    name: 'Fanta',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'sprite',
    name: 'Sprite',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'fernandes',
    name: 'Fernandes',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'heineken-00',
    name: 'Heineken 0.0',
    price: 4.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'redbull',
    name: 'RedBull',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'virgin-mojito',
    name: 'Virgin Mojito',
    price: 6.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'apple-juice',
    name: 'Apple Juice',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'orange-juice',
    name: 'Orange Juice',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'chocolate-milk',
    name: 'Chocolate Milk',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'iced-coffee',
    name: 'Iced Coffee',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'ice-tea-peach',
    name: 'Ice Tea Peach',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'ginger-ale',
    name: 'Ginger Ale',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'coffee-cappuccino',
    name: 'Coffee/Cappuccino',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'green-tea',
    name: 'Green Tea',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'still-water-250ml',
    name: 'Still Water 250ml',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'sparkling-water-250ml',
    name: 'Sparkling Water 250ml',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
  {
    id: 'still-water-15l',
    name: 'Still Water 1.5L',
    price: 6,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: '',
  },
]
