import type { MenuItem, MenuCategory } from '@/types'

export type MenuCategoryEntry = {
  id: MenuCategory
  label: string
  labelNl: string
  shortLabel: string
}

export const categoryLabels: Record<MenuCategory, { label: string; labelNl: string }> = {
  starters: {
    label: 'Indian Starters and Street Food in Den Haag',
    labelNl: 'Indiase Starters en Streetfood in Den Haag',
  },
  soups: {
    label: 'Indian Soups in Den Haag',
    labelNl: 'Indiase Soepen in Den Haag',
  },
  vegan: {
    label: 'Vegan Dishes',
    labelNl: 'Veganistische Gerechten',
  },
  tandoori: {
    label: 'Tandoori - Clay Oven Grill Specialties',
    labelNl: 'Tandoori Gerechten - Specialiteiten uit de Kleistenen Oven',
  },
  'veg-curries': {
    label: 'Vegetarian Indian Curries in Den Haag',
    labelNl: 'Vegetarische Indiase Curries in Den Haag',
  },
  chicken: {
    label: 'Chicken Curries in Den Haag',
    labelNl: 'Kip Curries in Den Haag',
  },
  'lamb-mutton': {
    label: 'Lamb and Mutton Curries in Den Haag',
    labelNl: 'Lam en Schapenvlees Curries in Den Haag',
  },
  'indo-chinese': {
    label: 'Indo-Chinese Dishes in Den Haag',
    labelNl: 'Indo-Chinese Gerechten in Den Haag',
  },
  biryani: {
    label: 'Biryani in Den Haag',
    labelNl: 'Biryani in Den Haag',
  },
  breads: {
    label: 'Indian Breads Baked Fresh in the Tandoor',
    labelNl: 'Indiaas Brood Vers Gebakken in de Tandoor',
  },
  'rice-sides': {
    label: 'Rice, Sides and Thali',
    labelNl: 'Rijst, Bijgerechten en Thali',
  },
  desserts: {
    label: 'Indian Desserts in Den Haag',
    labelNl: 'Indiase Desserts in Den Haag',
  },
  drinks: {
    label: 'Drinks and Lassi in Den Haag',
    labelNl: 'Dranken en Lassi in Den Haag',
  },
}

export const menuCategories: MenuCategoryEntry[] = [
  {
    id: 'starters',
    label: categoryLabels['starters'].label,
    labelNl: categoryLabels['starters'].labelNl,
    shortLabel: 'Starters',
  },
  {
    id: 'soups',
    label: categoryLabels['soups'].label,
    labelNl: categoryLabels['soups'].labelNl,
    shortLabel: 'Soups',
  },
  {
    id: 'vegan',
    label: 'Vegan Dishes',
    labelNl: 'Veganistische Gerechten',
    shortLabel: 'Vegan',
  },
  {
    id: 'tandoori',
    label: categoryLabels['tandoori'].label,
    labelNl: categoryLabels['tandoori'].labelNl,
    shortLabel: 'Tandoori',
  },
  {
    id: 'veg-curries',
    label: categoryLabels['veg-curries'].label,
    labelNl: categoryLabels['veg-curries'].labelNl,
    shortLabel: 'Veg Curries',
  },
  {
    id: 'chicken',
    label: categoryLabels['chicken'].label,
    labelNl: categoryLabels['chicken'].labelNl,
    shortLabel: 'Chicken',
  },
  {
    id: 'lamb-mutton',
    label: categoryLabels['lamb-mutton'].label,
    labelNl: categoryLabels['lamb-mutton'].labelNl,
    shortLabel: 'Lamb & Mutton',
  },
  {
    id: 'indo-chinese',
    label: categoryLabels['indo-chinese'].label,
    labelNl: categoryLabels['indo-chinese'].labelNl,
    shortLabel: 'Indo-Chinese',
  },
  {
    id: 'biryani',
    label: categoryLabels['biryani'].label,
    labelNl: categoryLabels['biryani'].labelNl,
    shortLabel: 'Biryani',
  },
  {
    id: 'breads',
    label: categoryLabels['breads'].label,
    labelNl: categoryLabels['breads'].labelNl,
    shortLabel: 'Breads',
  },
  {
    id: 'rice-sides',
    label: categoryLabels['rice-sides'].label,
    labelNl: categoryLabels['rice-sides'].labelNl,
    shortLabel: 'Rice & Sides',
  },
  {
    id: 'desserts',
    label: categoryLabels['desserts'].label,
    labelNl: categoryLabels['desserts'].labelNl,
    shortLabel: 'Desserts',
  },
  {
    id: 'drinks',
    label: categoryLabels['drinks'].label,
    labelNl: categoryLabels['drinks'].labelNl,
    shortLabel: 'Drinks',
  },
]

export const menuItems: MenuItem[] = [
  // ─── STARTERS ────────────────────────────────────────────────────────────
  {
    id: 'onion-bhaji',
    name: 'Onion Bhaji',
    price: 8,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/onion-bhaji.webp',
    description: 'Crispy golden fritters made with fresh onions and aromatic spices. A classic Indian starter in Den Haag.',
  },
  {
    id: 'samosa',
    name: 'Samosa (Veg/Lamb/Chicken)',
    price: 8,
    category: 'starters',
    dietary: ['halal'],
    image: '/images/dishes/veg-samosa.webp',
    description: 'Golden pastry filled with spiced potato and peas, fried fresh. A classic halal Indian starter in Den Haag.',
  },
  {
    id: 'veg-samosa-chaat',
    name: 'Veg Samosa Chaat',
    price: 10,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/samosa-chaat.webp',
    description: 'Crispy samosa broken open and topped with yogurt, chutney and chaat masala. Authentic Indian street food in Den Haag.',
  },
  {
    id: 'pani-puri',
    name: 'Pani Puri',
    price: 8,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/pani-puri.webp',
    description: 'Hollow crispy shells filled with spiced potato and tangy tamarind water. Authentic Indian street food in Den Haag.',
  },
  {
    id: 'dahi-puri',
    name: 'Dahi Puri',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dahi-puri.webp',
    description: 'Soft puris filled with spiced potato and dipped in sweet yogurt. Authentic Indian street food served in Den Haag.',
  },
  {
    id: 'aloo-tikki',
    name: 'Aloo Tikki',
    price: 8,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/aloo-tikki.webp',
    description: 'Pan-fried spiced potato patties served with mint chutney and yogurt. A popular halal Indian starter in Den Haag.',
  },
  {
    id: 'papdi-chaat',
    name: 'Papdi Chaat',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/papdi-chaat.webp',
    description: 'Crispy wafers topped with chickpeas, yogurt, tamarind and mint chutney. Classic Indian chaat in Den Haag.',
  },
  {
    id: 'mixed-chaat',
    name: 'Mixed Chaat',
    price: 12,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-chaat.webp',
    description: 'A generous platter of Den Haag street food favourites - pani puri, papdi chaat and aloo tikki from Chopras Indian Restaurant.',
  },
  {
    id: 'plain-papad',
    name: 'Plain Papad',
    price: 3.5,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/plain-papad.webp',
    description: 'Thin crispy lentil wafers - a traditional Indian starter served fresh at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'masala-papad',
    name: 'Masala Papad',
    price: 5,
    category: 'starters',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/masala-papad.webp',
    description: 'Crispy papad topped with fresh onions, tomatoes and chaat masala. A tangy Indian starter Den Haag guests love.',
  },

  // ─── TANDOORI ────────────────────────────────────────────────────────────
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-tikka.webp',
    description: 'Fresh cottage cheese marinated in spiced yogurt and chargrilled. Authentic vegetarian tandoori dish in Den Haag.',
  },
  {
    id: 'malai-soya-chaap',
    name: 'Malai Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-soya-chap.webp',
    description: 'Soya chaap marinated in creamy malai and mild spices, slow-grilled in our clay oven. Rich vegetarian dish Den Haag.',
  },
  {
    id: 'achari-soya-chaap',
    name: 'Achari Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/soya-chaap-achari.webp',
    description: 'Soya chaap marinated in tangy pickling spices and chargrilled in the clay oven. Authentic vegan dish Den Haag.',
  },
  {
    id: 'tandoori-prawn-fish',
    name: 'Tandoori Prawn/Fish',
    price: 24.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-prawns.webp',
    description: 'Fresh prawns or fish marinated in spiced yogurt and chargrilled in our tandoor. Halal seafood specialty Den Haag.',
  },
  {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-chicken.webp',
    description: 'Whole leg marinated overnight in yogurt and spices, chargrilled in our clay oven. Authentic tandoori Den Haag.',
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka.webp',
    description: 'Boneless halal chicken marinated in yogurt and spices, grilled in the tandoor clay oven. Halal chicken tikka Den Haag.',
  },
  {
    id: 'chicken-malai-tikka',
    name: 'Chicken Malai Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-malai-tikka.webp',
    description: 'Boneless halal chicken marinated in rich cream and mild spices, slow-grilled in our tandoor. Soft and smoky Den Haag favourite.',
  },
  {
    id: 'chicken-hariyali-tikka',
    name: 'Chicken Hariyali Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-hariyali-tikka.webp',
    description: 'Halal chicken marinated in fresh coriander and mint, chargrilled in the clay oven. Vivid green tikka Den Haag.',
  },
  {
    id: 'chicken-lasooni-tikka',
    name: 'Chicken Lasooni Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-lasooni-tikka.webp',
    description: 'Halal chicken marinated in a bold garlic and spice blend, chargrilled in the tandoor. Pungent, smoky tikka Den Haag.',
  },
  {
    id: 'lamb-seekh-kebab',
    name: 'Lamb Seekh Kebab',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-kebab.webp',
    description: 'Minced halal lamb mixed with fresh herbs and spices, grilled on skewers in our clay oven. Halal seekh kebab Den Haag.',
  },
  {
    id: 'chicken-seekh-kebab',
    name: 'Chicken Seekh Kebab',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-seekh-kebab.webp',
    description: 'Minced halal chicken blended with fresh herbs and spices, chargrilled on skewers in the tandoor. Authentic Den Haag kebab.',
  },
  {
    id: 'chopras-non-veg-platter',
    name: 'Chopras Non Veg Platter',
    price: 30,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chopras-non-veg-platter.webp',
    description: 'A generous tandoori selection from Chopras Indian Restaurant Den Haag - chicken tikka, seekh kebab and tandoori chicken.',
  },

  // ─── SOUPS ───────────────────────────────────────────────────────────────
  {
    id: 'tomato-soup',
    name: 'Tomato Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/tomato-soup.webp',
    description: 'Slow-cooked fresh tomato soup with Indian spices and a hint of cream. Warming Indian soup at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'lentil-soup',
    name: 'Lentil Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/dal-soup.webp',
    description: 'Homemade yellow lentil soup tempered with cumin and fresh herbs. Authentic Indian lentil soup in Den Haag.',
  },
  {
    id: 'veg-manchow-soup',
    name: 'Veg Manchow Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/manchow-soup.webp',
    description: 'Wok-tossed vegetables in a spiced Indo Chinese broth with crispy noodles. Indo Chinese soup Den Haag.',
  },
  {
    id: 'chicken-soup',
    name: 'Chicken Soup',
    price: 8.5,
    category: 'soups',
    dietary: ['halal'],
    image: '/images/dishes/chicken-soup.webp',
    description: 'Warming homemade soup made with fresh spices and tender halal chicken. Authentic Indian chicken soup Den Haag.',
  },

  // ─── VEG CURRIES (Veg Curries + Paneer Curries) ──────────────────────────
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    price: 18.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-makhani.webp',
    description: 'Black lentils slow cooked overnight with butter and cream. Authentic Punjabi dal makhani in Den Haag.',
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    price: 15,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/dal-tadka.webp',
    description: 'Yellow lentils slow cooked and tempered with butter, cumin and garlic. A classic vegetarian Indian curry in Den Haag.',
  },
  {
    id: 'rajma-raseela',
    name: 'Rajma Raseela',
    price: 15,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/rajma-masala.webp',
    description: 'Red kidney beans cooked in a rich tomato and onion gravy. Traditional North Indian vegetarian curry Den Haag.',
  },
  {
    id: 'chana-masala',
    name: 'Chana Masala',
    price: 16,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/channa-masala.webp',
    description: 'Chickpeas slow cooked in a tangy tomato and spice gravy. Authentic vegan Indian curry in Den Haag.',
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    price: 14,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/aloo-gobhi.webp',
    description: 'Cauliflower and potato cooked with fresh turmeric and cumin. Classic vegetarian Indian food Den Haag, served hot.',
  },
  {
    id: 'aloo-jeera',
    name: 'Aloo Jeera',
    price: 12.5,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/aloo-jeera.webp',
    description: 'Potatoes tempered with cumin seeds and fresh coriander. A simple, clean North Indian vegetarian side Den Haag.',
  },
  {
    id: 'mixed-veg',
    name: 'Mixed Veg',
    price: 15,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mixed-veg.webp',
    description: 'Seasonal vegetables cooked in a light tomato and spice gravy. Fresh vegetarian curry at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    price: 14,
    category: 'veg-curries',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/bhandi-masala.webp',
    description: 'Fresh okra cooked with onions, tomatoes and Indian spices. Authentic vegetarian curry at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'baingan-bharta',
    name: 'Baingan Bharta',
    price: 14,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/baingan-bharta.webp',
    description: 'Fire-roasted aubergine mashed with fresh spices and tomatoes. Smoky, authentic North Indian vegetarian curry Den Haag.',
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    price: 18.5,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kofta.webp',
    description: 'Soft cottage cheese and potato dumplings in a rich, creamy tomato and cashew gravy. Vegetarian Indian curry Den Haag.',
  },
  // Paneer Curries (grouped under veg-curries)
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/palak-paneer.webp',
    description: 'Fresh paneer cubes simmered in a smooth, spiced spinach sauce. Classic vegetarian Indian curry Den Haag.',
  },
  {
    id: 'karahi-paneer',
    name: 'Karahi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/karahi-paneer.webp',
    description: 'Paneer cubes cooked with bell peppers and tomatoes in a spiced karahi gravy. Vegetarian Indian food Den Haag.',
  },
  {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/shahi-paneer.webp',
    description: 'Fresh cottage cheese in a rich, creamy tomato and cashew gravy. Authentic Mughlai vegetarian curry Den Haag.',
  },
  {
    id: 'handi-paneer',
    name: 'Handi Paneer',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/handi-paneer.webp',
    description: 'Fresh paneer slow cooked in a sealed clay pot with aromatic whole spices. North Indian vegetarian dish Den Haag.',
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-butter-masala.webp',
    description: 'Soft paneer in a rich, buttery tomato sauce with whole spices. Popular vegetarian Indian dish in Den Haag.',
  },
  {
    id: 'tawa-paneer-masala',
    name: 'Tawa Paneer Masala',
    price: 18,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tawa-paneer.webp',
    description: 'Paneer cooked on a hot tawa with peppers, onions and robust Indian spices. Authentic vegetarian curry Den Haag.',
  },
  {
    id: 'chopras-special-paneer',
    name: 'Chopras Special Paneer',
    price: 20,
    category: 'veg-curries',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chopras-special-paneer.webp',
    description: 'Chopras Indian Restaurant house recipe - paneer in a layered spice gravy unique to our Den Haag kitchen.',
  },

  // ─── CHICKEN ─────────────────────────────────────────────────────────────
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    price: 20,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/butter-chicken.webp',
    description: 'Tender halal chicken in a rich, slow-cooked tomato and cream sauce. Den Haag most loved authentic chicken curry.',
  },
  {
    id: 'karahi-chicken',
    name: 'Karahi Chicken',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/kadai-chicken.webp',
    description: 'Halal chicken cooked with fresh tomatoes and peppers in a spiced karahi. Authentic North Indian chicken curry Den Haag.',
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-curry.webp',
    description: 'Classic halal chicken cooked in a homemade onion and tomato gravy. Authentic Indian chicken curry Den Haag.',
  },
  {
    id: 'chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    price: 20,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-masala.webp',
    description: 'Chargrilled chicken pieces in a creamy spiced tomato gravy. Classic halal Indian chicken curry in Den Haag.',
  },
  {
    id: 'chicken-handi',
    name: 'Chicken Handi',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-handi.webp',
    description: 'Slow-cooked halal chicken sealed in a clay pot with aromatic whole spices. North Indian specialty Den Haag.',
  },
  {
    id: 'chicken-vindaloo',
    name: 'Chicken Vindaloo',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-vindaloo.webp',
    description: 'Fiery halal chicken cooked in a bold Goan-style vinegar and spice gravy. Authentic Indian vindaloo Den Haag.',
  },
  {
    id: 'chicken-methi-malai',
    name: 'Chicken Methi Malai',
    price: 18,
    category: 'chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-methi-malai.webp',
    description: 'Tender halal chicken cooked with fragrant fenugreek leaves in a creamy sauce. Authentic North Indian chicken curry Den Haag.',
  },

  // ─── LAMB & MUTTON ───────────────────────────────────────────────────────
  {
    id: 'mutton-rogan-josh',
    name: 'Mutton Rogan Josh',
    price: 22.5,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-rogan-josh.webp',
    description: 'Slow-cooked halal lamb in a deep Kashmiri spice gravy. Authentic rogan josh at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'mutton-vindaloo',
    name: 'Mutton Vindaloo',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-vindaloo.webp',
    description: 'Fiery halal mutton cooked in a bold vinegar and spice gravy. Authentic Indian mutton vindaloo Den Haag.',
  },
  {
    id: 'tawa-mutton-masala',
    name: 'Tawa Mutton Masala',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/tawa-mutton-masala.webp',
    description: 'Halal mutton cooked on a hot tawa with peppers and robust spices. Authentic Indian lamb masala Den Haag.',
  },
  {
    id: 'mutton-karahi',
    name: 'Mutton Karahi',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-karahi.webp',
    description: 'Halal mutton cooked with fresh tomatoes and peppers in a spiced karahi gravy. Classic Indian lamb curry Den Haag.',
  },
  {
    id: 'mutton-korma',
    name: 'Mutton Korma',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/mutton-korma.webp',
    description: 'Halal lamb slow cooked in a mild, creamy almond and saffron sauce. Authentic Indian korma Den Haag.',
  },
  {
    id: 'mutton-handi',
    name: 'Mutton Handi',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/handi-mutton.webp',
    description: 'Halal mutton slow cooked in a sealed clay pot with whole spices and fresh herbs. Rich Indian lamb handi Den Haag.',
  },
  {
    id: 'rara-gosht',
    name: 'Rara Gosht',
    price: 25,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/rara-gosht.webp',
    description: 'Tender halal lamb cooked with minced mutton in a deeply spiced gravy. Bold authentic Indian lamb Den Haag.',
  },
  {
    id: 'keema-saag',
    name: 'Keema Saag',
    price: 22,
    category: 'lamb-mutton',
    dietary: ['halal'],
    image: '/images/dishes/keema-saag.webp',
    description: 'Minced halal lamb cooked with fresh spinach in a fragrant spiced gravy. Classic North Indian keema saag Den Haag.',
  },

  // ─── INDO-CHINESE ────────────────────────────────────────────────────────
  {
    id: 'veg-spring-roll',
    name: 'Veg Spring Roll',
    price: 10,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-spring-roll.webp',
    description: 'Crispy golden rolls filled with seasoned vegetables, served with Indo Chinese dipping sauce. Street food Den Haag.',
  },
  {
    id: 'chicken-spring-roll',
    name: 'Chicken Spring Roll',
    price: 11,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chicken-spring-roll.webp',
    description: 'Crispy golden rolls filled with spiced halal chicken, served with sweet chilli sauce. Indo Chinese food Den Haag.',
  },
  {
    id: 'chilli-paneer',
    name: 'Chilli Paneer',
    price: 18,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chilli-paneer.webp',
    description: 'Crispy paneer wok-tossed with peppers and onions in a bold Indo Chinese sauce. Authentic Indo Chinese food Den Haag.',
  },
  {
    id: 'chilli-chicken',
    name: 'Chilli Chicken',
    price: 20,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chilli-chicken.webp',
    description: 'Halal chicken wok-tossed with green chillies and soy sauce. Classic Indo Chinese dish at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'veg-noodles',
    name: 'Veg Noodles',
    price: 14.5,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-noodles.webp',
    description: 'Stir-fried noodles with fresh vegetables in Indo Chinese style. Authentic Indian Chinese food in Den Haag.',
  },

  // ─── BIRYANI ─────────────────────────────────────────────────────────────
  {
    id: 'veg-biryani',
    name: 'Veg Biryani',
    price: 15,
    category: 'biryani',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/veg-biryani.webp',
    description: 'Fresh seasonal vegetables layered with aromatic saffron basmati rice and whole spices. Authentic vegetarian biryani Den Haag.',
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    price: 19,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/chicken-biryani.webp',
    description: 'Halal chicken slow cooked with saffron basmati rice and whole spices. Authentic dum biryani Den Haag.',
  },
  {
    id: 'prawn-biryani',
    name: 'Prawn Biryani',
    price: 23,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/prawns-biryani.webp',
    description: 'Fresh prawns layered with fragrant saffron basmati rice and aromatic whole spices. Authentic seafood biryani Den Haag.',
  },
  {
    id: 'lamb-biryani',
    name: 'Lamb Biryani',
    price: 22,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/muton-biryani.webp',
    description: 'Halal lamb slow cooked with fragrant saffron basmati rice. Authentic Indian lamb biryani in Den Haag.',
  },

  // ─── BREADS (Bread + Rolls) ───────────────────────────────────────────────
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    price: 3,
    category: 'breads',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/tandoori-roti.webp',
    description: 'Whole wheat flatbread baked fresh in our tandoor clay oven. Authentic Indian bread at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'butter-roti',
    name: 'Butter Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tandoori-butter-roti.webp',
    description: 'Soft whole wheat roti brushed with fresh butter, hot from the tandoor. Classic Indian bread Den Haag.',
  },
  {
    id: 'onion-roti',
    name: 'Onion Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/onion-tandoori-roti.webp',
    description: 'Whole wheat bread stuffed with spiced onions and baked in the clay oven. Authentic Indian roti Den Haag.',
  },
  {
    id: 'garlic-roti',
    name: 'Garlic Roti',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-roti.webp',
    description: 'Whole wheat roti topped with fresh garlic and herbs, tandoor baked. Fragrant Indian bread Den Haag.',
  },
  {
    id: 'missi-roti',
    name: 'Missi Roti',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/missi-roti.webp',
    description: 'Chickpea flour and wheat flatbread with fresh herbs and spices. Traditional North Indian bread Den Haag.',
  },
  {
    id: 'lachha-paratha',
    name: 'Lachha Paratha',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/laccha-paratha.webp',
    description: 'Flaky layered whole wheat paratha cooked to a golden crisp. Classic North Indian bread Den Haag.',
  },
  {
    id: 'pudina-paratha',
    name: 'Pudina Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mint-paratha.webp',
    description: 'Layered paratha infused with fresh mint and spices. Aromatic Indian flatbread at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-paratha.webp',
    description: 'Whole wheat bread stuffed with spiced mashed potato and cooked with butter. Classic Indian aloo paratha Den Haag.',
  },
  {
    id: 'paneer-paratha',
    name: 'Paneer Paratha',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-paratha.webp',
    description: 'Whole wheat paratha stuffed with crumbled spiced paneer and baked in the clay oven. Vegetarian Indian bread Den Haag.',
  },
  {
    id: 'plain-naan',
    name: 'Plain Naan',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-naan.webp',
    description: 'Soft leavened flatbread baked fresh in our tandoor. Classic Indian naan bread served in Den Haag.',
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/butter-naan.webp',
    description: 'Soft tandoor-baked naan brushed generously with fresh butter. Classic Indian bread at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'garlic-naan',
    name: 'Garlic Naan',
    price: 4.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-naan.webp',
    description: 'Soft naan topped with fresh garlic and coriander, hot from the tandoor. Most popular Indian bread in Den Haag.',
  },
  {
    id: 'paneer-naan',
    name: 'Paneer Naan',
    price: 6,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-naan.webp',
    description: 'Soft naan stuffed with crumbled spiced paneer and baked fresh in the tandoor. Vegetarian Indian bread Den Haag.',
  },
  {
    id: 'cheese-naan',
    name: 'Cheese Naan',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cheese-naan.webp',
    description: 'Soft naan stuffed with melted cheese and baked in the clay oven. Rich Indian bread Den Haag.',
  },
  {
    id: 'keema-naan',
    name: 'Keema Naan',
    price: 7,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/keema-naan.webp',
    description: 'Naan stuffed with spiced minced halal lamb and fresh herbs. Authentic Indian keema naan Den Haag.',
  },
  // Rolls (grouped under breads)
  {
    id: 'paneer-roll',
    name: 'Paneer Roll',
    price: 12,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-roll.webp',
    description: 'Tandoor-grilled paneer wrapped in fresh roti with mint chutney and spiced onions. Vegetarian Indian wrap Den Haag.',
  },
  {
    id: 'egg-kathi-roll',
    name: 'Egg Kathi Roll',
    price: 12,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/egg-roll.webp',
    description: 'Fluffy egg wrapped in tandoor roti with spiced onions and tangy chutney. Classic Indian kathi roll Den Haag.',
  },
  {
    id: 'chicken-tikka-roll',
    name: 'Chicken Tikka Roll',
    price: 14,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-roll.webp',
    description: 'Tandoor-grilled halal chicken wrapped in fresh roti with onions and mint chutney. Halal Indian wrap Den Haag.',
  },
  {
    id: 'mutton-seekh-roll',
    name: 'Mutton Seekh Roll',
    price: 16,
    category: 'breads',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-roll.webp',
    description: 'Tender halal mutton seekh kebab wrapped in freshly baked roti with tangy chutneys. Authentic Indian wrap in Den Haag.',
  },

  // ─── RICE & SIDES (Rice non-biryani + Thali + Kids + Sides) ─────────────
  {
    id: 'steamed-rice',
    name: 'Steamed Rice',
    price: 7.5,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/steamed-rice.webp',
    description: 'Plain basmati rice steamed to perfection. A classic accompaniment to any Indian curry in Den Haag.',
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    price: 10,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/jeera-rice.webp',
    description: 'Basmati rice tempered with cumin seeds and fresh coriander. Fragrant Indian side dish served in Den Haag.',
  },
  {
    id: 'veg-fried-rice',
    name: 'Veg Fried Rice',
    price: 14,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-fried-rice.webp',
    description: 'Basmati rice wok-tossed with fresh vegetables in Indo Chinese style. Authentic Indian fried rice Den Haag.',
  },
  {
    id: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    price: 18,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/chicken-fried-rice.webp',
    description: 'Basmati rice wok-tossed with halal chicken and fresh vegetables in Indo Chinese style. Authentic fried rice Den Haag.',
  },
  {
    id: 'veg-thali',
    name: 'Veg Thali',
    price: 30,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-thali.webp',
    description: 'A complete vegetarian Indian meal - dal, curry, rice, naan and more. Authentic Indian thali experience in Den Haag.',
  },
  {
    id: 'non-veg-thali',
    name: 'Non Veg Thali',
    price: 35,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/non-veg-thali.webp',
    description: 'A hearty halal meal with curry, biryani, naan and more. Complete non-vegetarian thali at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'fries-nuggets',
    name: 'Fries & Nuggets',
    price: 7,
    category: 'rice-sides',
    dietary: ['halal'],
    image: '/images/dishes/fries-chicken-nuggets-kids.webp',
    description: 'Crispy golden fries and tender halal chicken nuggets. A popular kids and family side at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'onion-salad',
    name: 'Onion Salad',
    price: 5,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/onion-salad.webp',
    description: 'Freshly sliced onions with lemon and chaat masala. A simple Indian salad side at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'mixed-salad',
    name: 'Mixed Salad',
    price: 5,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mixed-salad.webp',
    description: 'A fresh mix of seasonal vegetables and salad greens. Light Indian sides Den Haag served at every table.',
  },
  {
    id: 'boondi-raita',
    name: 'Boondi Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/boondi-raita.webp',
    description: 'Crispy boondi pearls in cool, spiced yogurt. A refreshing Indian side dish at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'cucumber-raita',
    name: 'Cucumber Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cucumber-raita.webp',
    description: 'Cool yogurt mixed with fresh cucumber and roasted cumin. A cooling Indian side dish in Den Haag.',
  },
  {
    id: 'mixed-raita',
    name: 'Mixed Raita',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-raita.webp',
    description: 'Fresh yogurt mixed with cucumber, tomato and roasted cumin. A classic Indian sides Den Haag accompaniment.',
  },
  {
    id: 'green-chillies',
    name: 'Green Chillies',
    price: 2,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/green-chilli.webp',
    description: 'Fresh whole green chillies served as a fiery side. A traditional table accompaniment at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'mixed-pickle',
    name: 'Mixed Pickle',
    price: 3,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/mixed-pickle.webp',
    description: 'Traditional Indian mixed pickle with tangy spices. A classic Indian sides Den Haag accompaniment served at every table.',
  },
  {
    id: 'mint-chutney',
    name: 'Mint Chutney',
    price: 2,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '',
    description: 'Freshly blended green mint and coriander chutney. A cooling Indian condiment at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'tamarind-chutney',
    name: 'Tamarind Chutney',
    price: 2,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '',
    description: 'Sweet and tangy tamarind chutney with warming spices. An authentic Indian condiment served in Den Haag.',
  },
  {
    id: 'vinegar-onion',
    name: 'Vinegar Onion',
    price: 2,
    category: 'rice-sides',
    dietary: ['vegan', 'halal'],
    image: '',
    description: 'Sharp pickled onions in vinegar - a tangy, palate-cleansing side at Chopras Indian Restaurant Den Haag.',
  },

  // ─── DESSERTS ────────────────────────────────────────────────────────────
  {
    id: 'moong-dal-halwa',
    name: 'Moong Dal Halwa',
    price: 8,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/moong-dal-halwa.webp',
    description: 'Slow-cooked split moong lentil pudding with ghee and cardamom. Traditional Indian dessert Den Haag at its finest.',
  },
  {
    id: 'saffron-kheer',
    name: 'Saffron Kheer',
    price: 5.5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/saffron-kheer.webp',
    description: 'Creamy basmati rice pudding with saffron, cardamom and nuts. Classic Indian dessert served in Den Haag.',
  },
  {
    id: 'rasmalai',
    name: 'Rasmalai',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/rasmalai.webp',
    description: 'Soft cottage cheese dumplings soaked in saffron and cardamom milk. Classic Indian dessert Den Haag.',
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/gulab-jamun.webp',
    description: 'Soft milk dumplings soaked in rose and cardamom syrup. Classic Indian dessert at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'kulfi-pistachio',
    name: 'Kulfi Pistachio',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/pista-kulfi.webp',
    description: 'Traditional slow-churned Indian ice cream with rich pistachio flavour. Authentic Indian dessert in Den Haag.',
  },
  {
    id: 'kulfi-malai',
    name: 'Kulfi Malai',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kulfi.webp',
    description: 'Rich, creamy traditional Indian kulfi with a classic malai flavour. Authentic Indian dessert in Den Haag.',
  },
  {
    id: 'kulfi-coconut',
    name: 'Kulfi Coconut',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/coconut-kulfi.webp',
    description: 'Traditional handmade kulfi with creamy coconut. Authentic Indian ice cream at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'kulfi-mango',
    name: 'Kulfi Mango',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-kulfi.webp',
    description: 'Creamy handmade kulfi made with real Alphonso mango pulp. Authentic Indian mango dessert in Den Haag.',
  },
  {
    id: 'ice-cream-vanilla',
    name: 'Ice Cream Vanilla',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Classic creamy vanilla ice cream - a sweet, light dessert at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'ice-cream-chocolate',
    name: 'Ice Cream Chocolate',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Rich, velvety chocolate ice cream - a popular and crowd-pleasing dessert at Chopras Indian Restaurant Den Haag.',
  },
  {
    id: 'ice-cream-strawberry',
    name: 'Ice Cream Strawberry',
    price: 5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Fresh, vibrant strawberry ice cream - a sweet and fruity finish at Chopras Indian Restaurant Den Haag.',
  },

  // ─── DRINKS ──────────────────────────────────────────────────────────────
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    price: 6,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-lassi.webp',
    description: 'Thick, creamy yogurt drink blended with sweet Alphonso mango. Authentic Indian mango lassi in Den Haag.',
    isDrink: true,
  },
  {
    id: 'salted-lassi',
    name: 'Salted Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/salted-lassi.webp',
    description: 'Chilled yogurt drink with a pinch of salt and roasted cumin. Refreshing Indian drink Den Haag.',
    isDrink: true,
  },
  {
    id: 'sweet-lassi',
    name: 'Sweet Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/sweet-lassi.webp',
    description: 'Classic chilled yogurt drink lightly sweetened with sugar. Traditional Indian lassi at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'shikanji',
    name: 'Shikanji',
    price: 4.5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/shikanji.webp',
    description: 'Traditional Indian lemonade with black salt and spices - a refreshing Indian drink in Den Haag.',
    isDrink: true,
  },
  {
    id: 'jal-jeera',
    name: 'Jal Jeera',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/jal-jeera.webp',
    description: 'Tangy, spiced cumin and tamarind drink. A cooling authentic Indian street drink in Den Haag.',
    isDrink: true,
  },
  {
    id: 'masala-soda',
    name: 'Masala Soda',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/masala-soda.webp',
    description: 'Sparkling water with fresh lime and Indian chaat masala. A refreshing Indian street drink in Den Haag.',
    isDrink: true,
  },
  {
    id: 'masala-coke',
    name: 'Masala Coke',
    price: 4,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/masala-coke.webp',
    description: 'Coca-Cola mixed with fresh lime and chaat masala. A spiced twist on cola at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'masala-tea',
    name: 'Masala Tea',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/indian-masala-tea.webp',
    description: 'Freshly brewed Indian spiced tea with ginger, cardamom and milk. Authentic masala tea at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'thums-up',
    name: 'Thums Up',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/Thumps-Up-Den-Haag.avif',
    description: 'India iconic bold and caramel-rich cola - an authentic Indian drink experience at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'limca',
    name: 'Limca',
    price: 5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/Limca-Den-Haag.webp',
    description: 'Refreshing Indian lemon and lime flavoured soda. A taste of India at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'maaza',
    name: 'Maaza',
    price: 4,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/Maaza-Deg-haag-1.jpg',
    description: 'Sweet, thick Indian mango drink. Authentic Indian mango beverage at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'cola-cola-zero',
    name: 'Cola / Cola Zero',
    price: 3.5,
    category: 'drinks',
    dietary: ['vegan', 'halal'],
    image: '/images/dishes/coke-den-haag-scaled.webp',
    description: 'Classic Coca-Cola or sugar-free Cola Zero served ice cold at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'fanta',
    name: 'Fanta',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Fanta-Den-Haag.png',
    description: 'Bright, fizzy and refreshing orange Fanta served ice cold at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'sprite',
    name: 'Sprite',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Sprite-Den-Haag.jpg',
    description: 'Crisp, clean and refreshing lemon-lime Sprite served ice cold at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'fernandes',
    name: 'Fernandes',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Fernandes-Den-Haag.jpg',
    description: 'Popular Dutch favourite Fernandes soda in a range of fruity flavours served at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'heineken-00',
    name: 'Heineken 0.0',
    price: 4.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/heineken-zero-Den-HAag.webp',
    description: 'Crisp, full-flavoured alcohol-free Heineken lager. A refreshing halal beer option at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'redbull',
    name: 'RedBull',
    price: 4,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/redbull.jpg',
    description: 'RedBull energy drink served cold at Chopras Indian Restaurant Den Haag for a refreshing boost.',
    isDrink: true,
  },
  {
    id: 'virgin-mojito',
    name: 'Virgin Mojito',
    price: 6.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Fresh mint, lime and soda - a refreshing alcohol-free mocktail at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'apple-juice',
    name: 'Apple Juice',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Chilled, naturally sweet apple juice - a refreshing non-alcoholic drink at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'orange-juice',
    name: 'Orange Juice',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Orange-Juice-Den-Haag.jpg',
    description: 'Fresh, chilled orange juice - a bright and vitamin-rich drink at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'chocolate-milk',
    name: 'Chocolate Milk',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Chocolate-Milk-Den-Haag.jpg',
    description: 'Rich, creamy chocolate milk served chilled - a favourite with younger guests at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'iced-coffee',
    name: 'Iced Coffee',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Chilled brewed coffee over ice - a smooth and refreshing drink at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'ice-tea-peach',
    name: 'Ice Tea Peach',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Iced-Tea-Peach.webp',
    description: 'Chilled, lightly sweet peach iced tea - a refreshing non-alcoholic drink at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'ginger-ale',
    name: 'Ginger Ale',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Ginger-Ale-Den-Haag.png',
    description: 'Crisp, naturally spiced ginger ale - a sharp and refreshing drink served at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'coffee-cappuccino',
    name: 'Coffee/Cappuccino',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cappuccino.webp',
    description: 'Freshly brewed rich coffee or a creamy, frothy cappuccino served at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'green-tea',
    name: 'Green Tea',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Delicate, light and calming green tea brewed fresh and served warm at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'still-water-250ml',
    name: 'Still Water 250ml',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Still-Water-Den-Haag.jpg',
    description: 'Fresh, clean still mineral water served cold - a pure and simple drink at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'sparkling-water-250ml',
    name: 'Sparkling Water 250ml',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Sparkling-Water-Den-Haag.png',
    description: 'Crisp and clean sparkling water served chilled - a refreshing drink option at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
  {
    id: 'still-water-15l',
    name: 'Still Water 1.5L',
    price: 6,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Still-Water-Den-Haag.jpg',
    description: 'Large 1.5L still mineral water - ideal for families and groups dining at Chopras Indian Restaurant Den Haag.',
    isDrink: true,
  },
]
