import type { MenuItem, MenuCategory } from '@/types'

export type MenuCategoryEntry = {
  id: MenuCategory
  label: string
  labelNl: string
  shortLabel: string
}

export const categoryLabels: Record<MenuCategory, { label: string; labelNl: string }> = {
  starters: {
    label: 'Indian Starters and Street Food in Den Haag',
    labelNl: 'Indiase Starters en Streetfood in Den Haag',
  },
  soups: {
    label: 'Indian Soups in Den Haag',
    labelNl: 'Indiase Soepen in Den Haag',
  },
  tandoori: {
    label: 'Tandoori in Den Haag  -  Clay Oven Grill Specialties',
    labelNl: 'Indiase Tandoori Gerechten in Den Haag  -  Specialiteiten uit de Kleistenen Oven',
  },
  'mains-veg': {
    label: 'Vegetarian Indian Curries in Den Haag',
    labelNl: 'Vegetarische Indiase Curries in Den Haag',
  },
  'mains-chicken': {
    label: 'Chicken Curries in Den Haag',
    labelNl: 'Kip Curries in Den Haag',
  },
  'mains-lamb': {
    label: 'Lamb and Mutton Curries in Den Haag',
    labelNl: 'Lam en Schapenvlees Curries in Den Haag',
  },
  'indo-chinese': {
    label: 'Indo-Chinese Dishes in Den Haag',
    labelNl: 'Indo-Chinese Gerechten in Den Haag',
  },
  biryani: {
    label: 'Biryani in Den Haag',
    labelNl: 'Biryani in Den Haag',
  },
  breads: {
    label: 'Indian Breads Baked Fresh in the Tandoor',
    labelNl: 'Indiaas Brood Vers Gebakken in de Tandoor',
  },
  'rice-sides': {
    label: 'Rice and Sides',
    labelNl: 'Rijst en Bijgerechten',
  },
  desserts: {
    label: 'Indian Desserts in Den Haag',
    labelNl: 'Indiase Desserts in Den Haag',
  },
  drinks: {
    label: 'Drinks and Lassi in Den Haag',
    labelNl: 'Dranken en Lassi in Den Haag',
  },
}

export const menuItems: MenuItem[] = [
  // ─── STARTERS ────────────────────────────────────────────────────────────
  {
    id: 'onion-bhaji',
    name: 'Onion Bhaji',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/onion-bhaji.webp',
    description:
      'Crispy onion fritters seasoned with authentic Indian spices, deep fried to golden perfection and served with fresh mint and tangy tamarind chutney.',
  },
  {
    id: 'samosa',
    name: 'Samosa (Veg, Lamb, Chicken)',
    price: 8,
    category: 'starters',
    dietary: ['halal'],
    image: '/images/dishes/veg-samosa.webp',
    description:
      'Crisp triangular samosas stuffed with a flavourful mix of spiced potatoes, chickpeas or minced meat, fried until perfectly crunchy.',
  },
  {
    id: 'veg-samosa-chaat',
    name: 'Veg Samosa Chaat',
    price: 10,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/samosa-chaat.webp',
    description:
      'A crushed samosa topped with cool yogurt, chickpeas, fresh mint, coriander, tamarind chutney and mild spices.',
  },
  {
    id: 'pani-puri',
    name: 'Pani Puri',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/pani-puri.webp',
    description:
      'Crispy hollow puris filled with spicy potato and chickpea mix served with tangy mint and tamarind water.',
  },
  {
    id: 'dahi-puri',
    name: 'Dahi Puri',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dahi-puri.webp',
    description:
      'Crispy puris filled with potatoes and chickpeas topped with cool yogurt, mint, tamarind chutney and mild Indian spices.',
  },
  {
    id: 'aloo-tikki',
    name: 'Aloo Tikki',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-tikki.webp',
    description:
      'Golden shallow fried potato patties seasoned with aromatic Indian spices, served with mint and tamarind chutney.',
  },
  {
    id: 'papdi-chaat',
    name: 'Papdi Chaat',
    price: 8,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/papdi-chaat.webp',
    description:
      'Crispy flour crackers topped with potatoes, chickpeas, yogurt, mint chutney, tamarind chutney and mild Indian spices.',
  },
  {
    id: 'mixed-chaat',
    name: 'Mixed Chaat',
    price: 12,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-chaat.webp',
    description:
      'A flavourful chaat platter featuring samosa, aloo tikki, crushed papdi, yogurt, mint and tamarind chutney with mild Indian spices.',
  },
  {
    id: 'plain-papad',
    name: 'Plain Papad',
    price: 3.5,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-papad.webp',
    description:
      'Thin and crispy roasted lentil cracker lightly seasoned for a mild and crunchy Indian snack experience.',
  },
  {
    id: 'masala-papad',
    name: 'Masala Papad',
    price: 5,
    category: 'starters',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/masala-papad.webp',
    description: 'Crispy lentil cracker topped with onions, tomatoes, coriander and mild Indian spices.',
  },

  // ─── SOUPS ───────────────────────────────────────────────────────────────
  {
    id: 'tomato-soup',
    name: 'Tomato Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tomato-soup.webp',
    description:
      'A creamy tomato based Indian soup made with fresh tomatoes, mild spices, herbs and a smooth buttery texture.',
  },
  {
    id: 'lentil-soup',
    name: 'Lentil Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-soup.webp',
    description:
      'A classic Indian yellow lentil soup slow cooked with garlic, ginger, mild spices and herbs.',
  },
  {
    id: 'veg-manchow-soup',
    name: 'Veg Manchow Soup',
    price: 7.5,
    category: 'soups',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/manchow-soup.webp',
    description:
      'An Indo-Chinese vegetable soup made with mixed vegetables, crispy noodles, soy, garlic, ginger and medium Asian spices.',
  },
  {
    id: 'chicken-soup',
    name: 'Chicken Soup',
    price: 8.5,
    category: 'soups',
    dietary: ['halal'],
    image: '/images/dishes/chicken-soup.webp',
    description:
      'A flavourful Indian style chicken soup made with shredded chicken, garlic, ginger, herbs and mild spices.',
  },

  // ─── TANDOORI ────────────────────────────────────────────────────────────
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-tikka.webp',
    description:
      'Soft Indian paneer cubes marinated in yogurt, ginger, garlic, lemon and mild spices then grilled in the clay tandoor with onions and peppers.',
  },
  {
    id: 'malai-soya-chaap',
    name: 'Malai Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-soya-chap.webp',
    description:
      'Tender soya chaap pieces marinated in creamy yogurt, cashew paste, mild spices and herbs then grilled in the tandoor.',
  },
  {
    id: 'achari-soya-chaap',
    name: 'Achari Soya Chaap',
    price: 18,
    category: 'tandoori',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/soya-chaap-achari.webp',
    description:
      'Soya chaap marinated in Indian pickle spices, mustard, lemon, yogurt and medium hot flavours then grilled in the tandoor.',
  },
  {
    id: 'tandoori-prawn-fish',
    name: 'Tandoori Prawn/Fish',
    price: 24.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-prawns.webp',
    description:
      'Fresh prawns or fish fillets marinated in yogurt, lemon, garlic, ginger and medium Indian spices then roasted in the clay tandoor.',
  },
  {
    id: 'tandoori-chicken',
    name: 'Tandoori Chicken',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/tandoori-chicken.webp',
    description:
      'Chicken on the bone marinated overnight in yogurt, lemon, garlic, ginger and medium hot Indian spices then grilled in the tandoor.',
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka.webp',
    description:
      'Boneless chicken fillets marinated in yogurt, lemon, garlic, ginger and medium Indian spices then roasted in the tandoor.',
  },
  {
    id: 'chicken-malai-tikka',
    name: 'Chicken Malai Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-malai-tikka.webp',
    description:
      'Creamy boneless chicken pieces marinated with yogurt, cream, cheese, garlic, ginger and mild spices then grilled in the tandoor.',
  },
  {
    id: 'chicken-hariyali-tikka',
    name: 'Chicken Hariyali Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-hariyali-tikka.webp',
    description:
      'Green marinated boneless chicken blended with spinach, coriander, mint, yogurt, garlic, ginger and medium spices then tandoor grilled.',
  },
  {
    id: 'chicken-lasooni-tikka',
    name: 'Chicken Lasooni Tikka',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-lasooni-tikka.webp',
    description:
      'Garlic rich tandoori chicken marinated in yogurt, lemon, fresh garlic paste, ginger and mild to medium spices then roasted in the tandoor.',
  },
  {
    id: 'lambs-seekh-kebab',
    name: 'Lambs Seekh Kebab',
    price: 22.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/mutton-seekh-kebab.webp',
    description:
      'Minced lamb blended with onions, coriander, herbs, garlic, ginger and medium spices then grilled on skewers in the clay oven.',
  },
  {
    id: 'chicken-seekh-kebab',
    name: 'Chicken Seekh Kebab',
    price: 20.5,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chicken-seekh-kebab.webp',
    description:
      'Minced chicken mixed with onions, coriander, herbs, garlic, ginger and mild to medium spices then grilled on skewers in the tandoor.',
  },
  {
    id: 'chopras-non-veg-platter',
    name: "Chopra's Non Veg Platter",
    price: 30,
    category: 'tandoori',
    dietary: ['halal'],
    image: '/images/dishes/chopras-non-veg-platter.webp',
    description:
      'A premium tandoori platter featuring chicken tikka, malai tikka, hariyali tikka, seekh kebab and tandoori chicken.',
  },

  // ─── VEG CURRIES ─────────────────────────────────────────────────────────
  {
    id: 'dal-makhani',
    name: 'Dal Makhani',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-makhani.webp',
    description:
      'Slow cooked black lentils and kidney beans simmered overnight with butter, cream, tomato and mild spices.',
  },
  {
    id: 'dal-tadka',
    name: 'Dal Tadka',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/dal-tadka.webp',
    description:
      'Yellow lentils tempered with cumin, garlic, dried red chilli and fresh coriander in ghee.',
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/palak-paneer.webp',
    description:
      'Fresh paneer cubes in a smooth spinach gravy with garlic, ginger, cream and mild spices.',
  },
  {
    id: 'paneer-butter-masala',
    name: 'Paneer Butter Masala',
    price: 16,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/paneer-butter-masala.webp',
    description: 'Soft paneer in a rich buttery tomato and cream sauce with mild aromatic spices.',
  },
  {
    id: 'paneer-kadai',
    name: 'Paneer Kadai',
    price: 16,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/karahi-paneer.webp',
    description: 'Paneer cooked with onions, peppers, tomatoes and bold kadai spices.',
  },
  {
    id: 'paneer-tikka-masala',
    name: 'Paneer Tikka Masala',
    price: 16,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Tandoor grilled paneer cubes in a smoky tomato and cream masala sauce.',
  },
  {
    id: 'malai-kofta',
    name: 'Malai Kofta',
    price: 16,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/Malai Kofta.webp',
    description:
      'Soft cottage cheese and potato dumplings in a rich creamy tomato and cashew gravy.',
  },
  {
    id: 'shahi-paneer',
    name: 'Shahi Paneer',
    price: 16,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/shahi-paneer.webp',
    description:
      'Paneer cubes in a rich Mughal style gravy with cream, cashew and mild aromatic spices.',
  },
  {
    id: 'aloo-gobi',
    name: 'Aloo Gobi',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-gobhi.webp',
    description:
      'Potatoes and cauliflower dry cooked with turmeric, cumin, coriander and onion gravy.',
  },
  {
    id: 'aloo-jeera',
    name: 'Aloo Jeera',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/aloo-jeera.webp',
    description: 'Potatoes sauteed with cumin seeds, mild spices and fresh herbs.',
  },
  {
    id: 'mixed-veg',
    name: 'Mixed Veg',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-veg.webp',
    description: 'Seasonal vegetables cooked in a spiced tomato and onion gravy.',
  },
  {
    id: 'bhindi-masala',
    name: 'Bhindi Masala',
    price: 16,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/bhandi-masala.webp',
    description:
      'Tender okra cooked with onions, tomatoes, ginger, garlic and mild Indian spices.',
  },
  {
    id: 'aloo-palak',
    name: 'Aloo Palak',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Potatoes cooked in a smooth spiced spinach sauce with garlic and ginger.',
  },
  {
    id: 'palak-corn',
    name: 'Palak Corn',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Sweet corn kernels cooked in a creamy spiced spinach sauce.',
  },
  {
    id: 'matar-paneer',
    name: 'Matar Paneer',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Paneer and green peas cooked in a mild spiced tomato and onion gravy.',
  },
  {
    id: 'chana-masala',
    name: 'Chana Masala',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/channa-masala.webp',
    description: 'Chickpeas cooked in a tangy spiced tomato and onion masala.',
  },
  {
    id: 'rajma',
    name: 'Rajma',
    price: 15,
    category: 'mains-veg',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/rajma-masala.webp',
    description: 'Red kidney beans slow cooked in a rich onion, tomato and spice gravy.',
  },

  // ─── CHICKEN ─────────────────────────────────────────────────────────────
  {
    id: 'butter-chicken',
    name: 'Butter Chicken',
    price: 18.5,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '/images/dishes/butter-chicken.webp',
    description:
      'Tandoor roasted chicken in a rich buttery tomato cream sauce with mild aromatic spices.',
  },
  {
    id: 'chicken-tikka-masala',
    name: 'Chicken Tikka Masala',
    price: 18.5,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-tikka-masala.webp',
    description:
      'Tandoor grilled chicken tikka in a smoky tomato cream masala sauce with medium spices.',
  },
  {
    id: 'chicken-kadai',
    name: 'Chicken Kadai',
    price: 18,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '/images/dishes/kadai-chicken.webp',
    description: 'Chicken cooked with onions, peppers, tomatoes and bold kadai spices.',
  },
  {
    id: 'chicken-korma',
    name: 'Chicken Korma',
    price: 18,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '',
    description:
      'Tender chicken in a mild creamy sauce with cashews, coconut and gentle aromatic spices.',
  },
  {
    id: 'chicken-curry',
    name: 'Chicken Curry',
    price: 17,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '/images/dishes/chicken-curry.webp',
    description: 'Classic Indian chicken curry cooked in a spiced onion and tomato gravy.',
  },
  {
    id: 'chicken-saag',
    name: 'Chicken Saag',
    price: 18,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '',
    description: 'Chicken cooked in a smooth spiced spinach and herb gravy.',
  },
  {
    id: 'chicken-do-pyaza',
    name: 'Chicken Do Pyaza',
    price: 18,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '',
    description: 'Chicken cooked with double the onions, tomatoes and medium Indian spices.',
  },
  {
    id: 'chicken-rogan-josh',
    name: 'Chicken Rogan Josh',
    price: 18,
    category: 'mains-chicken',
    dietary: ['halal'],
    image: '',
    description:
      'Chicken slow cooked in a bold Kashmiri spiced gravy with whole aromatic spices.',
  },

  // ─── LAMB AND MUTTON ─────────────────────────────────────────────────────
  {
    id: 'lamb-rogan-josh',
    name: 'Lamb Rogan Josh',
    price: 20,
    category: 'mains-lamb',
    dietary: ['halal'],
    image: '/images/dishes/mutton-rogan-josh.webp',
    description:
      'Tender lamb slow cooked in a bold Kashmiri spiced gravy with whole aromatic spices.',
  },
  {
    id: 'lamb-curry',
    name: 'Lamb Curry',
    price: 19,
    category: 'mains-lamb',
    dietary: ['halal'],
    image: '',
    description: 'Classic lamb curry in a rich spiced onion and tomato gravy.',
  },
  {
    id: 'lamb-saag',
    name: 'Lamb Saag',
    price: 20,
    category: 'mains-lamb',
    dietary: ['halal'],
    image: '',
    description: 'Lamb cooked in a smooth spiced spinach gravy.',
  },
  {
    id: 'lamb-korma',
    name: 'Lamb Korma',
    price: 20,
    category: 'mains-lamb',
    dietary: ['halal'],
    image: '/images/dishes/mutton-korma.webp',
    description: 'Tender lamb in a mild creamy cashew and aromatic spice sauce.',
  },
  {
    id: 'lamb-kadai',
    name: 'Lamb Kadai',
    price: 20,
    category: 'mains-lamb',
    dietary: ['halal'],
    image: '/images/dishes/mutton-karahi.webp',
    description: 'Lamb cooked with onions, peppers, tomatoes and kadai spices.',
  },
  {
    id: 'keema-matar',
    name: 'Keema Matar',
    price: 19,
    category: 'mains-lamb',
    dietary: ['halal'],
    image: '',
    description: 'Spiced minced lamb cooked with green peas in a rich onion and tomato gravy.',
  },

  // ─── INDO-CHINESE ────────────────────────────────────────────────────────
  {
    id: 'veg-fried-rice',
    name: 'Veg Fried Rice',
    price: 12,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-fried-rice.webp',
    description: 'Wok tossed rice with mixed vegetables, soy, garlic and mild Asian spices.',
  },
  {
    id: 'chicken-fried-rice',
    name: 'Chicken Fried Rice',
    price: 14,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chicken-fried-rice.webp',
    description: 'Wok tossed rice with chicken, egg, soy, garlic and Asian spices.',
  },
  {
    id: 'veg-hakka-noodles',
    name: 'Veg Hakka Noodles',
    price: 12,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-noodles.webp',
    description:
      'Stir fried noodles with mixed vegetables, soy, garlic and medium Asian spices.',
  },
  {
    id: 'chicken-hakka-noodles',
    name: 'Chicken Hakka Noodles',
    price: 14,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '',
    description: 'Stir fried noodles with chicken, soy, garlic and medium Asian spices.',
  },
  {
    id: 'veg-manchurian',
    name: 'Veg Manchurian',
    price: 13,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Crispy vegetable balls in a tangy Indo-Chinese Manchurian sauce.',
  },
  {
    id: 'chicken-manchurian',
    name: 'Chicken Manchurian',
    price: 15,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '',
    description: 'Crispy chicken in a bold Indo-Chinese Manchurian gravy.',
  },
  {
    id: 'chilli-paneer',
    name: 'Chilli Paneer',
    price: 15,
    category: 'indo-chinese',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/chilli-paneer.webp',
    description:
      'Crispy paneer tossed with peppers, onions and a spicy Indo-Chinese chilli sauce.',
  },
  {
    id: 'chilli-chicken',
    name: 'Chilli Chicken',
    price: 15,
    category: 'indo-chinese',
    dietary: ['halal'],
    image: '/images/dishes/chilli-chicken.webp',
    description: 'Crispy chicken tossed with peppers, onions and a bold spicy chilli sauce.',
  },

  // ─── BIRYANI ─────────────────────────────────────────────────────────────
  {
    id: 'veg-biryani',
    name: 'Veg Biryani',
    price: 16,
    category: 'biryani',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/veg-biryani.webp',
    description:
      'Fragrant basmati rice slow cooked with seasonal vegetables, whole spices and saffron in dum style.',
  },
  {
    id: 'chicken-biryani',
    name: 'Chicken Biryani',
    price: 18,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/chicken-biryani.webp',
    description:
      'Fragrant basmati rice slow cooked with marinated chicken, whole spices and saffron in dum style.',
  },
  {
    id: 'lamb-biryani',
    name: 'Lamb Biryani',
    price: 20,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/muton-biryani.webp',
    description:
      'Fragrant basmati rice slow cooked with tender lamb, whole spices and saffron in dum style.',
  },
  {
    id: 'prawn-biryani',
    name: 'Prawn Biryani',
    price: 22,
    category: 'biryani',
    dietary: ['halal'],
    image: '/images/dishes/prawns-biryani.webp',
    description:
      'Fragrant basmati rice slow cooked with marinated prawns, whole spices and saffron in dum style.',
  },

  // ─── BREADS ──────────────────────────────────────────────────────────────
  {
    id: 'plain-naan',
    name: 'Plain Naan',
    price: 3,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-naan.webp',
    description: 'Soft leavened bread baked fresh in the tandoor.',
  },
  {
    id: 'butter-naan',
    name: 'Butter Naan',
    price: 3.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/butter-naan.webp',
    description: 'Soft tandoor baked naan brushed with fresh butter.',
  },
  {
    id: 'garlic-naan',
    name: 'Garlic Naan',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/garlic-naan.webp',
    description: 'Tandoor baked naan topped with fresh garlic and coriander.',
  },
  {
    id: 'peshwari-naan',
    name: 'Peshwari Naan',
    price: 4.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Sweet tandoor naan filled with coconut, almond and raisins.',
  },
  {
    id: 'cheese-naan',
    name: 'Cheese Naan',
    price: 4.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/cheese-naan.webp',
    description: 'Tandoor naan stuffed with melted cheese.',
  },
  {
    id: 'cheese-garlic-naan',
    name: 'Cheese Garlic Naan',
    price: 5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Tandoor naan stuffed with cheese and topped with garlic and coriander.',
  },
  {
    id: 'tandoori-roti',
    name: 'Tandoori Roti',
    price: 2.5,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/tandoori-roti.webp',
    description: 'Whole wheat bread baked fresh in the clay tandoor.',
  },
  {
    id: 'paratha',
    name: 'Paratha',
    price: 4,
    category: 'breads',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/laccha-paratha.webp',
    description: 'Layered whole wheat flatbread cooked on the tawa with butter.',
  },

  // ─── RICE AND SIDES ──────────────────────────────────────────────────────
  {
    id: 'plain-rice',
    name: 'Plain Rice',
    price: 4,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/steamed-rice.webp',
    description: 'Steamed basmati rice.',
  },
  {
    id: 'jeera-rice',
    name: 'Jeera Rice',
    price: 5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/jeera-rice.webp',
    description: 'Basmati rice tempered with cumin seeds and mild spices.',
  },
  {
    id: 'raita',
    name: 'Raita',
    price: 4,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-raita.webp',
    description: 'Cool yogurt with cucumber, mint and mild spices.',
  },
  {
    id: 'papad',
    name: 'Papad',
    price: 2.5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/plain-papad.webp',
    description: 'Crispy roasted lentil cracker.',
  },
  {
    id: 'pickle',
    name: 'Pickle',
    price: 1.5,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-pickle.webp',
    description: 'Traditional Indian mixed pickle.',
  },
  {
    id: 'salad',
    name: 'Salad',
    price: 4,
    category: 'rice-sides',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mixed-salad.webp',
    description:
      'Fresh Indian salad with onions, cucumber, tomato, lemon and chaat masala.',
  },

  // ─── DESSERTS ────────────────────────────────────────────────────────────
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/gulab-jamun.webp',
    description:
      'Soft milk solid dumplings soaked in rose and cardamom sugar syrup, served warm.',
  },
  {
    id: 'rasmalai',
    name: 'Rasmalai',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/rasmalai.webp',
    description:
      'Soft cottage cheese dumplings soaked in chilled saffron and cardamom flavoured milk.',
  },
  {
    id: 'kulfi',
    name: 'Kulfi',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/malai-kulfi.webp',
    description:
      'Traditional Indian ice cream made with condensed milk, cardamom and pistachios.',
  },
  {
    id: 'mango-kulfi',
    name: 'Mango Kulfi',
    price: 6.5,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-kulfi.webp',
    description: 'Traditional Indian ice cream with fresh Alphonso mango and cardamom.',
  },
  {
    id: 'kheer',
    name: 'Kheer',
    price: 6,
    category: 'desserts',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/saffron-kheer.webp',
    description:
      'Slow cooked rice pudding with milk, sugar, cardamom, saffron and nuts.',
  },

  // ─── DRINKS ──────────────────────────────────────────────────────────────
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    price: 5.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/mango-lassi.webp',
    description: 'Chilled yogurt drink blended with sweet Alphonso mango.',
  },
  {
    id: 'sweet-lassi',
    name: 'Sweet Lassi',
    price: 5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/sweet-lassi.webp',
    description: 'Chilled sweet yogurt drink.',
  },
  {
    id: 'masala-chai',
    name: 'Masala Chai',
    price: 3.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '/images/dishes/indian-masala-tea.webp',
    description: 'Spiced Indian tea with milk, ginger, cardamom and cinnamon.',
  },
  {
    id: 'still-water',
    name: 'Still Water',
    price: 2,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Still mineral water.',
  },
  {
    id: 'sparkling-water',
    name: 'Sparkling Water',
    price: 2.5,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Sparkling mineral water.',
  },
  {
    id: 'soft-drink',
    name: 'Soft Drink',
    price: 3,
    category: 'drinks',
    dietary: ['veg', 'halal'],
    image: '',
    description: 'Choice of cola, lemonade or orange.',
  },
]

export const menuCategories: MenuCategoryEntry[] = [
  { id: 'starters', shortLabel: 'Starters', ...categoryLabels.starters },
  { id: 'soups', shortLabel: 'Soups', ...categoryLabels.soups },
  { id: 'tandoori', shortLabel: 'Tandoori', ...categoryLabels.tandoori },
  { id: 'mains-veg', shortLabel: 'Veg Curries', ...categoryLabels['mains-veg'] },
  { id: 'mains-chicken', shortLabel: 'Chicken', ...categoryLabels['mains-chicken'] },
  { id: 'mains-lamb', shortLabel: 'Lamb & Mutton', ...categoryLabels['mains-lamb'] },
  { id: 'indo-chinese', shortLabel: 'Indo-Chinese', ...categoryLabels['indo-chinese'] },
  { id: 'biryani', shortLabel: 'Biryani', ...categoryLabels.biryani },
  { id: 'breads', shortLabel: 'Breads', ...categoryLabels.breads },
  { id: 'rice-sides', shortLabel: 'Rice & Sides', ...categoryLabels['rice-sides'] },
  { id: 'desserts', shortLabel: 'Desserts', ...categoryLabels.desserts },
  { id: 'drinks', shortLabel: 'Drinks', ...categoryLabels.drinks },
]
